
INSERT INTO Group (name ) VALUES ('admin');
INSERT INTO User (name, email, pass ) VALUES ('admin','admin@yourdomain.com','admin','1');
INSERT INTO FieldType (name, type ) VALUES ('Text','1');
INSERT INTO FieldType (name, type ) VALUES ('Option','2');
INSERT INTO FieldType (name, type ) VALUES ('Check','3');
INSERT INTO FieldType (name, type ) VALUES ('Number','4');
INSERT INTO FieldType (name, type ) VALUES ('Date','5');
INSERT INTO FieldType (name, type ) VALUES ('Photo','6');
INSERT INTO FieldType (name, type ) VALUES ('Date Time','7');
INSERT INTO FieldType (name, type ) VALUES ('Time','8');
INSERT INTO GraphType (name,type) VALUES ('Cake','2');
INSERT INTO GraphType (name,type) VALUES ('Bar','1');
INSERT INTO GraphType (name,type) VALUES ('Timeline','3');
INSERT INTO GraphTypeFieldType (graphType, fieldType ) VALUES ('2','2');
INSERT INTO GraphTypeFieldType (graphType, fieldType ) VALUES ('1','2');
INSERT INTO GraphTypeFieldType (graphType, fieldType ) VALUES ('2','3');
INSERT INTO GraphTypeFieldType (graphType, fieldType ) VALUES ('1','3');
INSERT INTO GraphTypeFieldType (graphType, fieldType ) VALUES ('2','4');
INSERT INTO GraphTypeFieldType (graphType, fieldType ) VALUES ('1','4');
INSERT INTO GraphTypeFieldType (graphType, fieldType ) VALUES ('3','5');
INSERT INTO GraphTypeFieldType (graphType, fieldType ) VALUES ('3','7');
