INSERT INTO Criadero (grupo, nombre ) VALUES ('3', 'KLEIN');
INSERT INTO Criadero (grupo, nombre ) VALUES ('3', 'INTA');
INSERT INTO Criadero (grupo, nombre ) VALUES ('3', 'BUCK');
INSERT INTO Criadero (grupo, nombre ) VALUES ('3', 'ACA');
INSERT INTO Criadero (grupo, nombre ) VALUES ('3', 'DON MARIO');
INSERT INTO Criadero (grupo, nombre ) VALUES ('3', 'LIMAGRAIN');
INSERT INTO Criadero (grupo, nombre ) VALUES ('3', 'QUILMES');
INSERT INTO Criadero (grupo, nombre ) VALUES ('3', 'MERCOSEED');
INSERT INTO Criadero (grupo, nombre ) VALUES ('3', 'NIDERA');
INSERT INTO Criadero (grupo, nombre ) VALUES ('3', 'BIOCERES');
INSERT INTO Criadero (grupo, nombre ) VALUES ('3', 'SURSEM');
INSERT INTO Criadero (grupo, nombre ) VALUES ('3', 'MONSANTO');
INSERT INTO Criadero (grupo, nombre ) VALUES ('3', 'AG SEED');
INSERT INTO Criadero (grupo, nombre ) VALUES ('3', 'FRANCIA');
INSERT INTO Criadero (grupo, nombre ) VALUES ('3', 'AGRISEED');
INSERT INTO Criadero (grupo, nombre ) VALUES ('3', 'SUESEM');
INSERT INTO Criadero (grupo, nombre ) VALUES ('3', 'Germany');
INSERT INTO Criadero (grupo, nombre ) VALUES ('3', 'France');
INSERT INTO Criadero (grupo, nombre ) VALUES ('3', 'United Kingdom');
INSERT INTO Criadero (grupo, nombre ) VALUES ('3', 'MALTERIA PAMPA');
INSERT INTO Criadero (grupo, nombre ) VALUES ('3', 'US GOV REP BY SEC');
